# Configurations to use when starting the database.

# The port that the primary server with write permissions listens on. Defaults to 3000.
primary_server_port: 3000

# The port that the read-only server listens on. Defaults to 3001.
read_only_server_port: 3001

# The maximum number of client connections to the primary server. Defaults to 1000.
max_connections_primary_server: 1000

# The maximum number of client connections to the read only server. Defaults to 1000.
max_connections_read_only_server: 1000

# The maximum size allowed for a key in bytes. This is 256 by default.
max_key_size_b: 256

# The maximum size allowed for a value in bytes. This is 65536 by default.
max_value_size_b: 65536

# The maximum number of stashes that can be created. This is 100 by default.
max_num_stashes: 100

# The delay in seconds between active expiration operations. This is the time between the end of the previous TTL batch cleanup to the start of the next TTL batch cleanup. This is 1 by default.
ttl_active_expire_delay_s: 1

# The number of keys to expire from each stash per active expiration operation. This is 100 by default.
ttl_active_expire_batch_size: 100

# Whether or not to store in-memory values off-heap. This is true by default.
use_off_heap_cache: true

# The maximum number of keys allowed in a stash before eviction. Defaults to 1000000.
default_max_key_count: 1000000

